WIP New post: Continuous Delivery Tools Revisited
madetech/blog pull request #167
Opened 2018-11-08 12:07 UTC by booyaa

2018-11-08 12:32 UTC, EThom73 requested changes
Left some reviews on there. Only a couple of readability/punctuation things.

2018-11-08 12:32 UTC, EThom73 commented on posts/continuous_delivery_tools_revisited.md
> +We'll see who are the new players, what are the new features to look for, and then review the advice we gave regarding choosing self-hosted over SaaS.
We'll see who the new players are,

2018-11-08 12:32 UTC, EThom73 commented on posts/continuous_delivery_tools_revisited.md
> +There's been a massive growth in this area with cloud independent solutions such as [Travis CI](https://travis-ci.org/), [Circle CI](https://circleci.com/). At the same time, Microsoft's Azure Pipeli
> At the same time, Microsoft's Azure Pipeline strong integration with their cloud offering.

missing a verb

2018-11-08 12:32 UTC, EThom73 commented on posts/continuous_delivery_tools_revisited.md
> +Container images have replaced buildpacks as the way to assure consistent versions of software releases. Look for baked in Docker support, to reduce the complexity and overhead of your pipeline.
>Look for baked in Docker support, to reduce the complexity and overhead of your pipeline.

Comma removal: Look for baked in Docker support to reduce the complexity and overhead of your pipeline.

2018-11-08 12:32 UTC, EThom73 commented on posts/continuous_delivery_tools_revisited.md
> +[GitHub](https://github.com/) who traditionally are the first step in building a CD pipeline now provides [GitHub Actions](https://developer.github.com/actions/) which allow pipeline functionality fr
> [GitHub](https://github.com/) who traditionally are the first step in building a CD pipeline now provides...

Comma usage: [GitHub](https://github.com/), who traditionally are the first step in building a CD pipeline, now provides

2018-11-08 12:32 UTC, EThom73 commented on posts/continuous_delivery_tools_revisited.md
> +The "deploy anywhere" approach of [Microsoft Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) (part of the Azure DevOps suite) means you can release software to any envi
>software to any environment 

add colon. software to any environment :

2018-11-08 12:32 UTC, EThom73 commented on posts/continuous_delivery_tools_revisited.md
> +The general advice from our original article remains the same, if it's a single product then SaaS will provide the least amount of friction whereas if you have multiple products or at enterprise scal
>The general advice from our original article remains the same, if it's a single product then SaaS will provide the least amount of friction whereas if you have multiple products or at enterprise scale then self-hosted is still worth considering.

couple of punctuation edits: The general advice from our original article remains the same. If it's a single product then SaaS will provide the least amount of friction, whereas if you have multiple products, or are at enterprise scale, then self-hosted is still worth considering.

2018-11-08 12:32 UTC, EThom73 commented on posts/continuous_delivery_tools_revisited.md
> +The self-hosted route is only feasible if you have a dedicated Ops team, as the chances are if your CD goes down, your CI will be down too (nearly all self-hosted solution provide CI/CD as an all-in-
edit: as the chances are **that** if your CD goes down

2018-11-08 13:09 UTC, adrianclay commented on posts/continuous_delivery_tools_revisited.md
> +There's been a massive growth in this area with cloud independent solutions such as [Travis CI](https://travis-ci.org/), [Circle CI](https://circleci.com/). On the flip side Microsoft's Azure Pipelin
There's [AWS CodeBuild](https://aws.amazon.com/codebuild/) too.

2018-11-08 13:11 UTC, EThom73 approved these changes

2018-11-08 18:22 UTC, SebAshton commented on posts/continuous_delivery_tools_revisited.md
> +There's been a massive growth in this area with cloud independent solutions such as [Travis CI](https://travis-ci.org/), [Circle CI](https://circleci.com/). On the flip side Microsoft's Azure Pipelin
If we're doing CD pipelines do we need to mention [AWS CodeDeploy](https://aws.amazon.com/codedeploy/) too

2018-11-08 18:24 UTC, SebAshton commented on posts/continuous_delivery_tools_revisited.md
> +There's been a massive growth in this area with cloud independent solutions such as [Travis CI](https://travis-ci.org/), [Circle CI](https://circleci.com/). On the flip side Microsoft's Azure Pipelin
Heroku do CI now too

2018-11-08 18:24 UTC, SebAshton commented on posts/continuous_delivery_tools_revisited.md
> +> We use docker images as a consistent way to base image for Ruby...
Could link to our Docker Hub

2018-11-08 18:25 UTC, SebAshton commented on posts/continuous_delivery_tools_revisited.md
> +Circle CI have turned workflow steps into shareable packages called Orbs.
Heroku has a deployment pipeline and offers review apps.

2018-11-08 18:58 UTC, SebAshton commented on posts/continuous_delivery_tools_revisited.md
> +> We use docker images as a consistent way to base image for Ruby...
https://hub.docker.com/u/madetech/

2018-11-09 16:32 UTC, DelphineGattaz commented on posts/continuous_delivery_tools_revisited.md
> +
I think we're missing a sentence here to explain why we're talking about Self-hosted or Saas. What is the angle for the next two sections? are we comparing?

2021-05-12 16:15 UTC, closed without merging